version: "3.2"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-master
    hostname: redis
    ports:
        - 6379:6379
    networks:
        - redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=1234
  myapp:
    image: myapp
    build: .
    container_name: myapp
    ports:
      - 8080:8080
    networks:
      - redis
    depends_on:
      - redis
networks:
  redis:
    driver: bridge
